env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "halium"

task:
  name: Halium
  timeout_in: 8760h
  persistent_worker:
    isolation:
      container:
        image: dopaemon/bionic:latest
        cpu: 4
        memory: 8G
        volumes:
          - /home/doraemon/HDD/CI/roms:/home/doraemon/HDD/CI/roms
          - /home/doraemon/HDD/CI/ccache:/home/doraemon/HDD/CI/ccache

  info_script:
    - lscpu
  info_disk_script:
    - ls /home/doraemon/HDD/CI/roms
  repo_sync_script:
    - cd /home/doraemon/HDD/CI/roms/11
    - repo init -q --no-repo-verify --depth=1 -u https://github.com/halium/android.git -b halium-10.0 -g default,-device,-mips,-darwin,-notdefault
    - git clone https://github.com/halium-exynos/local_manifest.git --depth 1 -b halium-10.0 .repo/local_manifests
    - repo sync -v -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -v -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)
  patch_halium_script:
    - cd /tmp/ci/lineage
    - hybris-patches/apply-patches.sh --mb
  start_build_halium_script:
    - source build/envsetup.sh
    - lunch lineage_on7xelte-userdebug
    - mka halium-boot -j$(nproc --all)
    - mka systemimage -j$(nproc --all)
