env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "halium"

task:
  name: Halium
  timeout_in: 8760h
  persistent_worker:
    isolation:
      container:
        image: dopaemon/bionic:latest
        cpu: 4
        memory: 8G
        volumes:
          - /home/doraemon/HDD/CI/roms:/home/doraemon/HDD/CI/roms
          - /home/doraemon/HDD/CI/ccache:/home/doraemon/HDD/CI/ccache

  info_script:
    - lscpu
  info_disk_script:
    - ls /home/doraemon/HDD/CI/roms
  start_build_halium_script:
    - cd /home/doraemon/HDD/CI/roms/halium/10/
    - . build/envsetup.sh
    - lunch lineage_on7xelte-userdebug
    - mka api-stubs-docs -j$(nproc --all)
    - mka hiddenapi-lists-docs -j$(nproc --all)
    - mka system-api-stubs-docs -j$(nproc --all)
    - mka test-api-stubs-docs -j$(nproc --all)
    - mka halium-boot -j$(nproc --all)
    - mka systemimage -j$(nproc --all)
