env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_conf: "ENCRYPTED[d41e7e645df0ba097fd15d17eaf8f35294181ac5c397f1d2481071cc9d2670eac3b5e33f52de2bc21b239fd29be03bc3]"

task:
  name: master
  timeout_in: 2h
  only_if: $CIRRUS_REPO_OWNER == 'halium-exynos'
  container:
    image: dopaemon/bionic:latest
    cpu: 8
    memory: 24G

  Install_Packages_Ubuntu_script:
    - rm -rf *
    - sudo apt-get update
    - sudo apt-get install -y ccache rclone git-lfs bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev pigz
  Git_Clone_From_Github_script:
    - git clone -b amd64 --single-branch https://github.com/EternalX-project/aarch64-linux-gnu.git gcc
    - echo "-------------------------------------------------------------------";
    - git clone -b lineage-16.0 --single-branch https://github.com/halium-exynos/CirrusCI.git origin
  Rclone_Configure_script:
    - mkdir -p ~/.config/rclone
    - echo "$rclone_conf" > ~/.config/rclone/rclone.conf
  Compile_Kernel_script:
    - cd /tmp/ci/origin
    - export CCACHE_DIR=/tmp/ccache
    - export CCACHE_EXEC=$(which ccache)
    - export USE_CCACHE=1
    - ccache -M 20G
    - ccache -o compression=true
    - ccache -z
    - ./build.sh
  Cache_background_script:
    - cd /tmp/ci/cirrus
    - ./monitor.sh
  Compile_Kernel2_script:
    - cd /tmp/ci/cirrus
    - ./build2.sh
